pull_request_rules:
  - name: Auto-merge pull request bot
    conditions:
      - -files~=\.github/.*
      - -files~=util/.*
      - base=master
      - -conflict
      - -closed
      - status-success=security_check
    actions:
      merge:
        strict: smart
        strict_method: merge
        method: squash
      comment:
        message: "Принято!"
