pull_request_rules:
  - name: Comment when circleci passes
    conditions:
      - -files~=\.github/.*
      - -files~=util/.*
      - base=master
      - -conflict
      - status-success=tests
    actions:
      merge:
        strict: smart
        strict_method: rebase
        method: squash
      comment:
        message: "Rebased, Squashed and Merged!"

