pull_request_rules:
  - name: Comment when circleci passes
    conditions:
      - files!=.circleci/*
      - files!=util/*
      - "status-success=ci/circleci: build"
    actions:
      comment:
        message: "OK"

