pull_request_rules:
  - name: Comment when circleci passes
    conditions:
      - -files~=\.github/.*
      - -files~=util/.*
      - "#status-success>=2"
    actions:
      comment:
        message: "OK"

