pull_request_rules:
  - name: Comment when circleci passes
    conditions:
      - -files~=\.github/.*
      - -files~=util/.*
      - "status-success=ci/circleci: build"
    actions:
      comment:
        message: "OK"

