pull_request_rules:
  - name: Comment when circleci passes
    conditions:
      - -files~=\.github/.*
      - -files~=util/.*
      "- status-success=Main / tests (pull_request)"
      "- status-success=Main / tests (pull_request) "
      "- status-success=Main / tests (push)"
    actions:
      comment:
        message: "OK"

