pull_request_rules:
  - name: Comment when circleci passes
    conditions:
      - -files~=\.github/.*
      - -files~=util/.*
      - status-success=tests
    actions:
      comment:
        message: "OK"

