pull_request_rules:
  - name: Comment when circleci passes
    conditions:
      - files~=task[1-6]/\w+\.sql
      - "status-success=ci/circleci: build"
    actions:
      comment:
        message: "OK"

